### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by ghost** [larrypsmith/Bitter#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ghost** [comment]
when we go to the signup/ login page there is no way for us to go back to the splash page. Probably want to add a link to the "bitter" text you have on the forms so that it leads you back to the splash page. 

the signin/signup page should follow this kind of format.  
<img width="410" alt="Screen Shot 2020-03-06 at 9 49 19 AM" src="https://user-images.githubusercontent.com/30717440/76108615-c3504080-5f8f-11ea-973f-e09535f2b421.png">

also you need a demo user

**Comment by larrypsmith** [comment]
I think I've completed all the Auth issues. The demo user is accessed through a separate button next to the log in and create account buttons on the splash page
